### ISSUE TITLE
Crashes on License Verification on first launch when installed from play store.

### ISSUE THREAD

**Issue by dipendrapkrl** [javiersantos/PiracyChecker#50]
Hi there, Thanks for the awesome library. 
 I am noticing a strange crash that can't even be caught. It happens when license check is enabled and the app has been launched for the very first time when installed from play store(doesn't happen if installed outside of play store). The crash never happens afterwards however. 

You can find the logs here: 
https://pastebin.com/NpN8DSvZ

Any help would be highly appreciated.

**Comment by dipendrapkrl** [comment]
I have provided the license key as is by grabbing from play store. 
The interesting fact is that it only crashes once. The very first time license based check is done.
Next time onward it works well. Now I am disabling this check for first few times so the app would not crash.

**Comment by dipendrapkrl** [comment]
This issue is legit. Please tell me what info I need to provide.

**Comment by jahirfiquitiva** [comment]
I just doubt you're using the right key, since the issue clearly states `InvalidKeySpecException` and that means you're using an incorrectly encripted license key. Most likely you're getting the incorrect one. Go to Google Play Developer Console -> Select your app -> Development Tools -> API and Services -> License Key .... It usually starts with something like: `MIIBIjANB` it also *must not* contain any spaces.

**Comment by imspikey** [comment]
@jahirfiquitiva  hello Im facing the same problem although I am sure that my key is correct here is my error log from firebase 

`Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException
Only the original thread that created a view hierarchy can touch its views.
android.view.ViewRootImpl.checkThread (ViewRootImpl.java:7352)
androidx.appcompat.app.AppCompatActivity.setContentView (Unknown Source)
standalone.smartkids.com.activities.WelcomeActivity.access$000 (Unknown Source)
standalone.smartkids.com.activities.WelcomeActivity$2.allow (Unknown Source)
com.github.javiersantos.piracychecker.PiracyChecker$callback$1.allow (Unknown Source)
com.github.javiersantos.piracychecker.PiracyChecker.blockIfUnauthorizedAppUninstalled (Unknown Source)
com.github.javiersantos.piracychecker.PiracyChecker.blockIfUnauthorizedAppUninstalled (Unknown Source)
com.github.javiersantos.piracychecker.PiracyChecker$verify$1.allow$13462e (Unknown Source)
com.github.javiersantos.licensing.LibraryValidator.handleResponse (Unknown Source)
com.github.javiersantos.licensing.LibraryChecker$ResultListener$2.run (Unknown Source)


This only happens when running for the first time and after downloading from google play store.
