### ISSUE TITLE
Attribution required?

### ISSUE THREAD

**Issue by bravo-delta** [javiersantos/PiracyChecker#8]
This library is licensed under Apache v2. Under normal circumstances I would add this to the about section of my app and give attribution.
In this case it seems counterproductive to give a broad hint to the cracker? What is your advice in this case?

**Comment by javiersantos** [comment]
I think a cracker won't be cared about the attributions in an app. They will just decompile the app and see some patterns in order to patch the license checker. So it doesn't matter if the library is listed or not in the app's credits, it will be as easy as checking the dependencies included when the app has been decompiled.
